development:
  adapter: postgresql
  database: dev_journal_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: dev_journal_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: dev_journal_production
  pool: 5
  timeout: 5000